#class Settings:
import pygame
pygame.init()

SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 800

MAIN_MENU_BUTTON_WIDTH: int = SCREEN_WIDTH * 3 // 10
MAIN_MENU_BUTTON_HEIGHT: int = SCREEN_HEIGHT // 10

CLICKER_MENU_BUTTON_WIDTH: int = SCREEN_WIDTH * 1.5 // 10
CLICKER_MENU_BUTTON_HEIGHT: int = SCREEN_HEIGHT // 15

CLICKER_UPGRADE_BUTTON_WIDTH: int = 400
CLICKER_UPGRADE_BUTTON_HEIGHT: int = 50
CLICKER_UPGRADE_BUTTON_INDENT: int = 10
CLICKER_UPGRADE_BUTTON_X: int = SCREEN_WIDTH - CLICKER_UPGRADE_BUTTON_INDENT * 2 - CLICKER_UPGRADE_BUTTON_WIDTH
CLICKER_UPGRADE_BUTTON_Y = 2
CLICKER_UPGRADE_BUTTON_Y: int = 30

MONSTERS_IN_CLICKER: list[str] = [
    'zombieMale',
    'zombieFemale',
    'zombieWild',
]
MONSTER_HP_IN_CLICKER: float = 10.0
SCALE_OF_MONSTERS_IN_CLICKER: int = 5

PLAYER_DAMAGE_IN_CLICKER: float = 1.0

BASIC_FONT = pygame.font.SysFont(None, 24)

